### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by 0x241F31** [mikeplus64/solid-typefu-router5#1]
Hi.
I found that there is router propety in return object of createSolidRouter functuon, but it is not the best way. So I'm searching for smthing like <Redirect /> or .navigate(). What is the way?

**Comment by mikeplus64** [comment]
> Hi.
> I found that there is router propety in return object of createSolidRouter functuon, but it is not the best way. So I'm searching for smthing like or .navigate(). What is the way?

The way I would recommend is to use `Link` where possible, but to access the internal [Router5 router](https://router5.js.org/) you can access on the return type of `createSolidRouter` `router.router5` which has a `.navigate()` method (and more, see the router5 docs). So in my project that uses this library I have:

```typescript
// router/index.ts
export const { Router, Provider, Link, router: { router5 }, hints } = createSolidRouter(routes, { ... })
```

I can add a `useRouter5()` method that uses the router `Context` to provide the same object, like how `useRoute` works, but I wasn't sure if I should because it simply isn't actually necessary to use `Context` at all there, and it can create bugs if you accidentally use it in a place where Solid can't provide the outer `Context` (IIRC this happened sometimes in event handlers and some effects).

**Comment by mikeplus64** [comment]
Btw, there is now a `.navigate` method returned by `createSolidRouter`. It takes the exact same type-safe `to` and `params` as the `Link` component.
