### ISSUE TITLE
Props don't change after navigation

### ISSUE THREAD

**Issue by 0x241F31** [mikeplus64/solid-typefu-router5#2]
Hi. I have routes:
```jsx
const routes = [
  {
    name: 'schedule',
    path: '/schedule',
    children: [
      {
        name: 'date',
        path: '/:date',
      },
    ],
  },
] as const;
```
and router
```jsx
export default function RouterProvider() {
  return (
    <Provider>
      <AppRoutes />
    </Provider>
  );
}
function AppRoutes() {
  const route = useRoute();
  return (
    <Router>
      {{
        fallback: NotFound,
        schedule: {
          render: Schedule,
          date: (owned) =>
            owned({
              render: ScheduleGrid,
              props: {
                date: () => route().params.date,
              },
            }),
        },
      }}
    </Router>
  );
}
```

and in `Schedule` component I'm using programmatical navigation:
```js
  createComputed(() => {
    navigateToDate(selectedDate());
  });

  function navigateToDate(date: Date) {
    router.router5.navigate('schedule.date', {
      date: encodeURI(dateFnsFormat(date, 'dd.MM.yyyy')),
    });
  }
```
`selectedDate` signal is changing, url too, but child component `ScheduleGrid` get props.date only once at initial render:
```js
export default function ScheduleGrid(props) {
  createComputed(() => {
    console.log('date in schedule grid is', props.date);
  });
```
Am I doing something wrong? Thanks in advance.

**Comment by 0x241F31** [comment]
By the way
```js
  const route = useRoute();
  createComputed(() => {
    console.log('date in schedule grid is', route().params.date);
  });
```
is working

**Comment by mikeplus64** [comment]
That definitely looks like it should work to me, I'll have a look. 

I think it might be worth adding a `useRouteParams` though which wraps the params in solid's `State` type so you get reactivity on individual params, but since your route is actually changing your `date` prop should also update so I don't think it's that.

**Comment by mikeplus64** [comment]
@MrFoxPro  So, I've done something pretty drastic which is to remove the "owned" router idiom entirely. Since the primary use case was to pass in router params, and TypeScript 4.1 now supports template string literals, I've made the library support parsing your routes' paths strings into params types which is then used for type-safe params in `Link` and in `Router`.

So in `Router` each `render` is now passed in a `{ children?: JSX.Element, params: THE_RELEVANT_PARAMS_TYPE_HERE }` as its props. 

I think that's probably a pretty poor explanation but if you check out the new example code here https://github.com/mikeplus64/solid-typefu-router5/blob/71c19e18cd5c55556a5a5d69472893fdced63b99/example/src/index.tsx#L123 you can see that `params` is now available to `render`. Strangely TypeScript does know the correct type and will yell at you if you type your `params` wrongly, but it still needs you to explicitly spell it out or else it complains about an implicit `any`.

**Comment by 0x241F31** [comment]
Thanks, @mikeplus64! I've updated package and now I have typescript error: 
![image](https://user-images.githubusercontent.com/17229619/101385446-a1e50200-38dd-11eb-8560-558d25b72ecf.png)
Do you have any ideas how it could be fixed?

**Comment by 0x241F31** [comment]
nevermind, I fixed it with placing routes inside configuration object

**Comment by mikeplus64** [comment]
FYI, I just pushed an update that fixes the inference as well. So you don't need the explicit type signatures on `render`/`fallback` any more. =D

**Comment by 0x241F31** [comment]
I tested now but props are not changing anyway
https://codesandbox.io/s/route-params-as-props-u0w2p?file=/src/index.tsx
Take a look at example if you have time please.
![router_bug](https://user-images.githubusercontent.com/17229619/101466655-347bb480-3963-11eb-8095-3dae994ed420.gif)

**Comment by mikeplus64** [comment]
@MrFoxPro ahh, the core problem there is the destructuring you have at the bottom. 

```typescript
// works
              render: (props) => <Child date={props.params.date} />

// your version
//              render: ({ params }) => <Child date={params.date} />
```

However, I do wonder if your version *should* work because in theory the `params` state object *itself* shouldn't be updating, but its properties should.

See https://codesandbox.io/s/route-params-as-props-forked-twioz?file=/src/index.tsx:2148-2230

Thanks for helping me test the library. =)

**Comment by 0x241F31** [comment]
Thank you
